version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Chrome for tests
      - apt-get update
      - apt-get install -y fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcups2 libgbm1 libgtk-3-0 libu2f-udev libvulkan1 libxcomposite1 libxdamage1 libxkbcommon0 libxrandr2 xdg-utils
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb
      - echo "Assigning environment variables"
      - sed -i "s|__API_BASE_URL__|${API_URL}|g" src/environments/environment.prod.ts
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@10.0.8
  build:
    commands:
      - echo "Building Angular project..."
      - ng build --configuration production
      - npm run test:ci
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/ui/ s3://iot-plant-app --delete
