version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Assigning environment variables"
      - - sed -i "s|__API_BASE_URL__|${API_URL}|g" src/environments/environment.prod.ts
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@10.0.8
  build:
    commands:
      - echo "Building Angular project..."
      - ng build --configuration production
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/ui/ s3://iot-plant-app --delete
